version: "3.8"

services:
  app:
    build: .
    image: pokedex-api:dev
    container_name: pokedex-app
    ports:
      - "3000:3000"
    env_file: 
      - ./.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./:/app:cached
      - prisma-data:/app/prisma
    networks:
      - pokenet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/pokemons"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis:7-alpine
    container_name: pokedex-redis
    ports:
      - "6379:6379"
    networks:
      - pokenet
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: pokedex-prometheus
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - pokenet

  grafana:
    image: grafana/grafana:latest
    container_name: pokedex-grafana
    ports:
      - "3001:3000" 
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/grafana:/etc/grafana/provisioning
    networks:
      - pokenet

volumes:
  prisma-data:

networks:
  pokenet:
