version: "3.8"
services:
  app:
    build: .
    image: pokedex-api:dev
    container_name: pokedex-app
    ports:
      - "3000:3000"
    env_file: 
      - ./.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - redis
    volumes:
      - ./:/app:cached
      - prisma-data:/app/prisma
    networks:
      - pokenet

  redis:
    image: redis:7-alpine
    container_name: pokedex-redis
    ports:
      - "6379:6379"
    networks:
      - pokenet

volumes:
  prisma-data:

networks:
  pokenet:
